# Generated by Django 5.0.4 on 2024-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedAppointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('zip', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('service', models.CharField(choices=[('Masajes', 'Masajes'), ('Drenajes', 'Drenajes'), ('Tratamientos', 'Tratamientos'), ('Depilación', 'Depilación')], default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email_address', models.CharField(default='', max_length=50)),
                ('question', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RequestAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(default='', max_length=50)),
                ('phone_number', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('zip', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('service', models.CharField(choices=[('Masajes', 'Masajes'), ('Drenajes', 'Drenajes'), ('Tratamientos', 'Tratamientos'), ('Depilación', 'Depilación')], default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('time', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
