# Generated by Django 5.0.4 on 2024-05-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0002_alter_approvedappointments_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerequest',
            name='last_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
