# Generated by Django 5.0.4 on 2024-06-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0004_alter_approvedappointments_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('document_signed', models.BooleanField(default=False)),
                ('sign_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
