# Generated by Django 5.0.4 on 2024-06-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0005_signeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
