# Generated by Django 5.0.4 on 2024-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0007_remove_signeddocument_document_signed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='condition_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Condition Name'),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='has_condition',
            field=models.BooleanField(default=False, verbose_name='Has Condition'),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
