# Generated by Django 5.0.4 on 2024-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0008_signeddocument_condition_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signeddocument',
            name='accept_photo',
            field=models.BooleanField(default=False, verbose_name='Accepts Pictures'),
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='accept_publishing',
            field=models.BooleanField(default=False, verbose_name='Accepts Publishing'),
        ),
    ]
