# Generated by Django 5.0.4 on 2024-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0009_signeddocument_accept_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signeddocument',
            name='condition_name',
        ),
        migrations.AddField(
            model_name='signeddocument',
            name='condition_names',
            field=models.TextField(blank=True, default='[]', verbose_name='Condition Names'),
        ),
    ]
