# Generated by Django 5.0.4 on 2024-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0012_alter_signeddocument_condition_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signeddocument',
            name='signature',
            field=models.ImageField(blank=True, default='', null=True, upload_to='signatures/'),
        ),
    ]
