# Generated by Django 5.0.4 on 2024-06-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0013_alter_signeddocument_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seen', models.DateTimeField(auto_now_add=True, verbose_name='Date Seen')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('treatment', models.CharField(blank=True, default='', max_length=100)),
                ('payment_type', models.CharField(choices=[('ATHMovil', 'ATHMovil'), ('Cash', 'Cash'), ('Credit', 'Credit')], default='', max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Price in dollars', max_digits=10)),
                ('comments', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
    ]
