# Generated by Django 5.0.4 on 2024-06-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0015_alter_clientlog_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlog',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clientlog',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
