# Generated by Django 5.0.4 on 2024-06-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0016_clientlog_email_clientlog_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signeddocument',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='phone_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
