# Generated by Django 5.0.4 on 2024-06-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0017_alter_signeddocument_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signeddocument',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='signeddocument',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
