# Generated by Django 5.0.4 on 2024-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0019_customerentry_delete_clientlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerentry',
            name='treatment',
            field=models.CharField(choices=[('Masaje Sueco', 'Masaje Sueco'), ('Post Operatorio', 'Post Operatorio'), ('Masaje Prenatal', 'Masaje Prenatal'), ('Masaje Profundo', 'Masaje Profundo'), ('Gold Detox', 'Gold Detox'), ('Vacuslim-48', 'Vacuslim-48'), ('Depilacion', 'Depilacion'), ('Maderoterapia', 'Maderoterapia'), ('Metaloterapia', 'Metaloterapia'), ('Drenaje Linfatico', 'Drenaje Linfatico'), ('Quiromasaje', 'Quiromasaje'), ('Copas Chinas', 'Copas Chinas'), ('Pistola de Masaje', 'Pistola de Masaje'), ('Maderoterapia Facial', 'Maderoterapia Facial'), ('Lipolaser', 'Lipolaser'), ('Vacumterapia', 'Vacumterapia'), ('LeBody', 'LeBody'), ('Otro', 'Otro')], default='', max_length=50),
        ),
    ]
