# Generated by Django 5.0.4 on 2024-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0022_appointments_remove_requestappointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=50)),
                ('nine', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
                ('ten', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
                ('eleven', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
                ('twelve', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
                ('one', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
                ('two', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
                ('three', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
                ('four', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
                ('five', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
