# Generated by Django 5.0.4 on 2024-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_app', '0027_alter_customerentry_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerentry',
            name='treatment',
            field=models.CharField(choices=[('Masaje Sueco', 'Masaje Sueco'), ('Post Operatorio', 'Post Operatorio'), ('Masaje Prenatal', 'Masaje Prenatal'), ('Masaje Profundo', 'Masaje Profundo'), ('Gold Detox', 'Gold Detox'), ('Vacuslim-48', 'Vacuslim-48'), ('Depilacion', 'Depilacion'), ('Maderoterapia', 'Maderoterapia'), ('Metaloterapia', 'Metaloterapia'), ('Drenaje Linfatico', 'Drenaje Linfatico'), ('Quiromasaje', 'Quiromasaje'), ('Copas Chinas', 'Copas Chinas'), ('Pistola de Masaje', 'Pistola de Masaje'), ('Maderoterapia Facial', 'Maderoterapia Facial'), ('Lipolaser', 'Lipolaser'), ('Vacumterapia', 'Vacumterapia'), ('LeBody', 'LeBody'), ('Mesoterapia', 'Mesoterapia'), ('Post Parto', 'Post Parto'), ('Otro', 'Otro')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='requestappointment',
            name='service',
            field=models.CharField(choices=[('Gold Detox (6 Secciones)', 'Gold Detox (6 Secciones)'), ('Metaloterapia (6 Secciones)', 'Metaloterapia (6 Secciones)'), ('Maderoterapia (6 Secciones)', 'Maderoterapia (6 Secciones)'), ('Masaje Sueco', 'Masaje Sueco'), ('Post-Operatorio', 'Post-Operatorio'), ('Masaje Prenatal', 'Masaje Prenatal'), ('Masaje Profundo', 'Masaje Profundo'), ('Gold Detox', 'Gold Detox'), ('Vacuslim-48', 'Vacuslim-48'), ('Depilación', 'Depilación'), ('Maderoterapia', 'Maderoterapia'), ('Metaloterapia', 'Metaloterapia'), ('Drenaje Linfático', 'Drenaje Linfático'), ('Quiromasaje', 'Quiromasaje'), ('Copas Chinas', 'Copas Chinas'), ('Pistola De Masaje', 'Pistola De Masaje'), ('Maderoterapia Facial', 'Maderoterapia Facial'), ('Lipoláser', 'Lipoláser'), ('Vacumterapia', 'Vacumterapia'), ('LeBody', 'LeBody'), ('Post Parto', 'Post Parto'), ('Mesoterapia', 'Mesoterapia')], default='', max_length=50),
        ),
    ]
